/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package milestonegameprojectv3;

/**
 *
 * @author Lenovo-Laptop
 */
public class HelpMenu extends javax.swing.JFrame {

    private MilestoneGame milestoneGame;

    /**
     * Creates new form HelpMenu
     */
    public HelpMenu(MilestoneGame milestoneGame) {
        this.milestoneGame = milestoneGame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        menuSoundOFF = new javax.swing.JToggleButton();
        menuSoundON = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(404, 404));
        getContentPane().setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\n\n\n\nRules:\n\n1.Collect all the pokeballs without to lose.\n2.You have 3 lifes and 3 levels.\n3.Collect all pokeballs  for the next level.\n4.You can kill only the small pokemons.\n5.Be careful! The big pokemons can kill you.\n6.Buttons: ← ↑ →  ,  Jump = Space, Fire = c");
        jTextArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 310, 290);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo-Laptop\\Desktop\\City University of London\\Java\\Semester 2 Spring\\GAME IN BOX2D IN JAVA\\MilestoneGameProjectV3\\data\\BackgroundHelpPikachu.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 0, 404, 390);

        menuSoundOFF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        menuSoundOFF.setText("SoundOFF");
        menuSoundOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSoundOFFActionPerformed(evt);
            }
        });
        getContentPane().add(menuSoundOFF);
        menuSoundOFF.setBounds(0, 340, 280, 50);

        menuSoundON.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        menuSoundON.setText("SoundON");
        menuSoundON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSoundONActionPerformed(evt);
            }
        });
        getContentPane().add(menuSoundON);
        menuSoundON.setBounds(0, 290, 280, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSoundONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSoundONActionPerformed
        milestoneGame.menuSoundON();
    }//GEN-LAST:event_menuSoundONActionPerformed

    private void menuSoundOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSoundOFFActionPerformed
        milestoneGame.menuSoundOFF();
    }//GEN-LAST:event_menuSoundOFFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpMenu().setVisible(true);
            }
        });
         */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton menuSoundOFF;
    private javax.swing.JToggleButton menuSoundON;
    // End of variables declaration//GEN-END:variables
}
