/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package milestonegameprojectv3;

public class MainMenu extends javax.swing.JFrame {

    private MilestoneGame milestoneGame;

    /**
     * Creates new form MainMenu
     */
    public MainMenu(MilestoneGame milestoneGame) {
        this.milestoneGame = milestoneGame;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        help = new javax.swing.JButton();
        newGame = new javax.swing.JButton();
        loadGame = new javax.swing.JButton();
        scoreRecords = new javax.swing.JButton();
        quit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        help.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        help.setText("Help");
        help.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        getContentPane().add(help);
        help.setBounds(20, 520, 220, 60);

        newGame.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        newGame.setText("New Game");
        newGame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        newGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameActionPerformed(evt);
            }
        });
        getContentPane().add(newGame);
        newGame.setBounds(20, 220, 280, 65);

        loadGame.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        loadGame.setText("Load Game");
        loadGame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        loadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGameActionPerformed(evt);
            }
        });
        getContentPane().add(loadGame);
        loadGame.setBounds(20, 310, 280, 65);

        scoreRecords.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        scoreRecords.setText("Records");
        scoreRecords.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        scoreRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreRecordsActionPerformed(evt);
            }
        });
        getContentPane().add(scoreRecords);
        scoreRecords.setBounds(20, 430, 220, 60);

        quit.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        quit.setText("Quit");
        quit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        getContentPane().add(quit);
        quit.setBounds(20, 610, 220, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo-Laptop\\Desktop\\City University of London\\Java\\Semester 2 Spring\\GAME IN BOX2D IN JAVA\\MilestoneGameProjectV3\\data\\BackgroundMainMenu.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, -580, 1410, 1920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameActionPerformed

        milestoneGame.playMilestoneGame();
        dispose(); //close (destroy) the JFrame
    }//GEN-LAST:event_newGameActionPerformed

    private void loadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadGameActionPerformed

    private void scoreRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreRecordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreRecordsActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        milestoneGame.HelpMenu();
    }//GEN-LAST:event_helpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });

    }
         */
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loadGame;
    private javax.swing.JButton newGame;
    private javax.swing.JButton quit;
    private javax.swing.JButton scoreRecords;
    // End of variables declaration//GEN-END:variables
}
